import { Tags } from '@vcomponents'
import styles from '@vstyles/home.module.css'
import { useState } from 'react'
import { resetIdCounter, Tab, TabList, TabPanel, Tabs } from 'react-tabs'

const ExperienceTabs: React.FC = () => {
  const [selectedTab, setSelectedTab] = useState(0)

  resetIdCounter()

  const tabs = [
    {
      idx: 0,
      name: 'Education',
      header: 'One',
      children: (
        <>
          <h3 className="my-0">Aalto University, Finland</h3>
          <p className={styles.pExp}>
            MSc. in Security and Cloud Computing,{' '}
            <span className="ml-2 font-mono tracking-wide">Sep 2021 - Present</span>
          </p>
          <p>School of Science</p>
          <h3 className="my-0">University Politehnica of Bucharest, Romania</h3>
          <p className={styles.pExp}>
            BSc. in Computer Engineering, <span className="ml-2 font-mono tracking-wide">Sep 2017 - Jul 2021</span>
          </p>
          <p className={styles.pExp}>GPA: 9.79/10</p>
          <h3 className="mb-0">Åbo Akademi University, Turku, Finland</h3>
          <p className={styles.pExp}>
            Erasmus+ Exchange Student in Computer Science,{' '}
            <span className="ml-2 font-mono tracking-wide">Aug 2019 - May 2020</span>
          </p>
          <p className={styles.pExp}>GPA: 5/5</p>
        </>
      ),
    },
    {
      idx: 1,
      name: 'Volunteering',
      children: (
        <>
          <h3 className="my-0">Codette</h3>
          <p className={styles.pExp}>
            Technical Trainer, <span className="ml-2 font-mono tracking-wide">Sep 2018 - Jun 2020</span>
          </p>
          <ul>
            <li>
              Contributed as a technical trainer by creating resources and delivering presentations at{' '}
              <strong>four editions of a web-technologies workshop</strong>, based on Angular, with a total of 80
              participants.
            </li>
            <li>
              Contributed as a designer by creating the branding, designing and implementing the website and creating
              the social media posts of a <strong>mentorship program</strong> for university students called Techtor.
            </li>
            <li>Contributed as a technical trainer at a mobile development workshop for 20 young children.</li>
          </ul>
          <Tags tags={['designing', 'training', 'documenting']} additionalClasses="bg-indigo-900" />
          <h3 className="mb-0">LSAC - Automatics and Computing Student League</h3>
          <p className={styles.pExp}>
            Graphic Designer, <span className="ml-2 font-mono tracking-wide">Feb 2018 - Feb 2019</span>
          </p>
          <ul>
            <li>
              Created posters and graphics for the student association events, with a{' '}
              <strong>reach of 3000 people</strong> and set the creative direction to a LSAC organised hackathon.
            </li>
            <li>
              Managed the fifth HackITAll edition, a student hackathon supported by Amazon, in the position of the{' '}
              <strong>Design Project Manager</strong>.
            </li>
            <li>Mentored new members and trained them through an Introduction to design workshop.</li>
          </ul>
          <Tags tags={['designing', 'managing', 'mentoring']} additionalClasses="bg-indigo-900" />
          <h3 className="mb-0">Coder Dojo</h3>
          <p className={styles.pExp}>
            Trainer, <span className="ml-2 font-mono tracking-wide">Sep 2018 - Jun 2019</span>
          </p>
          <p>
            Participated twice a month as a trainer at workshops for primary-school children where we taught basic
            programming using online tools, mainly Scratch.
          </p>
        </>
      ),
    },
    {
      idx: 2,
      name: 'AScI',
      children: (
        <>
          <h3 className="my-0">Aalto Science Institute</h3>
          <p className={styles.pExp}>
            Research Assistant in Human Computer Interaction department,{' '}
            <span className="ml-2 font-mono tracking-wide">Jun 2021 - Aug 2021</span>
          </p>
          <ul>
            <li>
              Worked on a <strong>Vue</strong> app, that scores a given website (screenshot or URL) on a set of UIX
              design metrics researched in the Aalto User Interfaces department. I have upgraded{' '}
              <strong>Webpack</strong> configurations and frontend dependencies, implemented result dynamic plotting and
              improved backend logging.
            </li>
            <li>
              Created a <strong>Figma</strong> plugin that communicates to the user a set of{' '}
              <strong>color palettes</strong> generated by a machine learning model that could improve their design. I
              have modeled and written the backend application using <strong>FastAPI</strong>, I have decided the data
              interfaces and collaborated with integrating the model.
            </li>
          </ul>
          <Tags tags={['Vue', 'Preact', 'tornado', 'FastAPI', 'Figma API']} additionalClasses="bg-indigo-900" />
        </>
      ),
    },
    {
      idx: 3,
      name: 'Postis',
      children: (
        <>
          <h3 className="my-0">Postis, Bucharest, Romania</h3>
          <p className={styles.pExp}>
            Junior Software Engineer, <span className="ml-2 font-mono tracking-wide">Sep 2020 - May 2021</span>
          </p>
          <ul>
            <li>
              Analyzing customer post-delivery text reviews in order to discover trends and associate them with business
              issues.
            </li>
            <li>
              Implemented <strong>internationalization</strong> and managed the frontend of a SaaS web platform.
            </li>
          </ul>
          <Tags tags={['AngularJS', 'Svelte', 'NLP', 'Python']} additionalClasses="bg-indigo-900" />
          <p className={styles.pExp}>
            Frontend Developer Intern, <span className="ml-2 font-mono tracking-wide">Jul 2018 - Sep 2018</span>
          </p>
          <p>
            Managed a delivery tracking web application of over <strong>50 000 orders</strong>, using Git versioning,
            AngularJS, Bootstrap, Grunt and proprietary REST APIs. Fixed interface bugs,{' '}
            <strong>shortened the load time </strong> by removing 7 unused dependencies and added 5 new client
            functionalities while pushing over 75 commits. <strong>Reduced main app size by 20%</strong> and an order
            tracking page by 90% by using ES6 instead of jQuery.
          </p>
          <Tags tags={['AngularJS', 'Bootstrap', 'REST APIs', 'ES6']} additionalClasses="bg-indigo-900" />
        </>
      ),
    },
    {
      idx: 4,
      name: 'GSoC',
      children: (
        <>
          <h3 className="my-0">Inkscape, Google Summer of Code 2020</h3>
          <p className={styles.pExp}>
            Remote Software Developer, <span className="ml-2 font-mono tracking-wide">Jun 2020 - Aug 2020</span>
          </p>
          <p>
            Developer for <strong>Inkscape</strong>, a vector design desktop application that follows the{' '}
            <strong>SVG</strong> standards. Worked on a <strong>C++</strong> dialog system refactoring project, with
            over 120 commits, <strong>6000 lines changed</strong>, reducing code length by 10%. The resulting change
            eliminated more than 12 active UX issues. Implementing the new dialog system consisted of removing old
            dependencies, standardising a design pattern and propagating document state. Specifically, this included{' '}
            <strong>over 20 features</strong>.
          </p>
          <Tags tags={['C++', 'GTK+', 'gtkmm', 'UX', 'refactoring']} additionalClasses="bg-indigo-900" />
          <h3 className="mb-0">Inkscape, Google Summer of Code 2019</h3>
          <p className={styles.pExp}>
            Remote Software Developer, <span className="ml-2 font-mono tracking-wide">May 2020 - Aug 2020</span>
          </p>
          <p>
            Implemented <strong>JavaScript polyfills</strong> that reproduce, in browsers, SVG functionality which
            exists in Inkscape but has been dropped by the <strong>SVG2 specification</strong> draft. Had over 60
            commits in 4 feature branches over 4 months, using JavaScript and the GTK+ toolkit. Implemented new
            functionality (paint servers preview dialog) as a starter point for future fill and stroke paint servers
            unification.
          </p>
          <Tags
            tags={['JavaScript', 'polyfills', 'SVG', 'GTK+', 'standardisation']}
            additionalClasses="bg-indigo-900"
          />
        </>
      ),
    },
    {
      idx: 5,
      name: 'Etsimo',
      children: (
        <>
          <h3 className="mt-0">Etsimo Healthcare Oy, Turku, Finland</h3>
          <p className={styles.pExp}>
            Junior Software Engineer, <span className="ml-2 font-mono tracking-wide">Jan 2020 - Jun 2020</span>
          </p>
          <p>
            Worked on improving RxJS state in an Angular user-facing app of the cer- tified Diagnosis Engine. Integrated
            dynamic translations with an existing Flask REST backend, <strong>reducing load time by 20%</strong>.
            Created, in a team of two, over 12 iterations, an intended-use <strong>conversational workflow</strong> demo
            of the Etsimo service capabilities, deployed from a <strong>Node.js server</strong> with a Preact chat
            interface. Written from the bottom up a new <strong>TypeScript library</strong> that exposes Etsimo’s API
            for developer use, helps with type checking for JavaScript apps and has automated{' '}
            <strong>unit tests</strong>.
          </p>
          <Tags
            tags={['API', 'Angular', 'RxJS', 'Preact', 'Flask', 'NodeJS', 'TypeScript']}
            additionalClasses="bg-indigo-900"
          />
        </>
      ),
    },
  ]

  return (
    <Tabs selectedIndex={selectedTab} onSelect={(idx: number) => setSelectedTab(idx)}>
      <TabList className="flex m-0 overflow-x-scroll text-gray-100 bg-indigo-900 border-2 border-b-0 cursor-pointer md:overflow-hidden">
        {tabs.map((tab) => (
          <Tab
            key={tab.idx}
            className={`${
              selectedTab === tab.idx ? 'bg-brand' : 'border-b-2'
            } list-none ml-0 mb-0 py-2 px-5 font-bold focus:outline-white mt-0`}
          >
            {tab.name}
          </Tab>
        ))}
        <div className="flex-grow block border-b-2"></div>
      </TabList>
      {tabs.map((tab) => (
        <TabPanel
          key={tab.idx}
          className={`w-full p-4 pt-8 border-2 border-t-0 ${selectedTab === tab.idx ? 'block' : 'hidden'}`}
        >
          {tab.children}
        </TabPanel>
      ))}
    </Tabs>
  )
}

export default ExperienceTabs
